// apps/web/src/components/FinalCta.tsx
import Link from "next/link";

const FinalCta = () => {
  return (
    <div className="relative py-20 md:py-40 bg-cover bg-center text-center text-white">
      <div className="relative container mx-auto px-6">
        <h2 className="font-cinzel text-4xl md:text-6xl font-bold drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
          Your Fate Is Unwritten
        </h2>
        <p className="font-cormorant italic text-2xl text-white/80 mt-6 max-w-3xl mx-auto drop-shadow-sm">
          The world of Aethel needs its Architects. Will you answer the call?
        </p>
        <div className="mt-10">
          <Link
            href="/login"
            className="inline-block px-6 py-4 font-bold font-cinzel tracking-wide bg-transparent rounded-md transition hover:bg-current/20 hover:shadow-xl duration-200 border border-white/20 backdrop-blur-sm"
          >
            Begin Your Journey
          </Link>
        </div>
      </div>
    </div>
  );
};

export default FinalCta;

// apps/web/src/components/landing/FinalCTA.svelte
<div class="relative py-20 md:py-40 bg-cover bg-center text-center text-white">
  <div class="relative container mx-auto px-6">
    <h2 class="font-cinzel text-4xl md:text-6xl font-bold drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
      Your Fate Is Unwritten
    </h2>
    <p class="font-cormorantI text-2xl text-white/80 mt-6 max-w-3xl mx-auto drop-shadow-sm">
      The world of Aethel needs its Architects. Will you answer the call?
    </p>
    <div class="mt-10">
      
      <a
        href="/login"
        class="inline-block px-6 py-4 font-bold font-cinzel tracking-wide bg-transparent rounded-md transition  hover:bg-current/20 hover:shadow-xl duration-200 border border-white/20 backdrop-blur-sm"
      >
        Begin Your Journey
      </a>
    </div>
  </div>
</div>
