// apps/web/src/components/Hero.svelte
<script>
import { hero } from "$lib/constants";
import { backgroundImage } from "$lib/stores/uiStore";
import { onMount } from "svelte";

const selected = hero[Math.floor(Math.random() * hero.length)];

const headingSentences = selected.heading
	.split(".")
	.map((s) => s.trim())
	.filter((s) => s.length > 0);

const loreIntro =
	selected.lore || "A world once governed by logic... now broken.";

onMount(() => {
	backgroundImage.set("url('/img/bg2.jpg')");
});
</script>

<div class="flex flex-col items-center justify-center min-h-[90vh] text-center px-4">
    
    <!-- Lore: Changed to white for better contrast on dark backgrounds -->
    <p class="font-cormorantI text-xl text-white/70 mb-4 drop-shadow">
      {loreIntro}
    </p>

    <!-- Heading: Added a blinking cursor for the "code" vibe -->
    <div class="font-cinzel text-5xl md:text-6xl font-bold text-white space-y-2 drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
      {#each headingSentences as sentence, i}
        <p>
          {sentence}.
          <!-- IMPROVEMENT: Add a blinking cursor only to the last sentence -->
          {#if i === headingSentences.length - 1}
            <span class="ml-1 animate-pulse">|</span>
          {/if}
        </p>
      {/each}
    </div>

    <!-- Subheading: No changes needed, already good -->
    <div class="font-cormorantI text-2xl text-white/80 px-6 mt-6 max-w-3xl drop-shadow-sm">
      {selected.subheading}
    </div>

    <!-- CTA: Enhanced the "glass" effect -->
    <div class="mt-10">
      <!-- IMPROVEMENT: Added backdrop-blur and a subtle border -->
      <a 
        href="/start" 
        class="bg-slate-700/30 text-white px-8 py-3 rounded-md transition font-ebg text-xl shadow-lg hover:bg-slate-700/60 hover:shadow-xl hover:scale-105 duration-200 border border-white/20 backdrop-blur-sm"
      >
        {selected.cta}
      </a>
    </div>

    <!-- Tagline: No changes needed -->
    {#if selected.tagline}
      <p class="mt-4 text-white/70 text-sm font-medium italic max-w-xl px-4">
        {selected.tagline}
      </p>
    {/if}
</div>

// apps/web/src/components/landing/Hero.tsx
import Link from "next/link";
import { Button } from "@/components/ui/button";

type HeroData = {
  heading?: string;
  lore?: string;
  subheading?: string;
  cta?: string;
};

export default function Hero({
  heroData = {},
  isLoaded = false,
}: {
  heroData?: HeroData;
  isLoaded?: boolean;
}) {
    const headingSentences = (heroData.heading ?? "")
    .split(".")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
    
    return (
        <section className="h-dvh flex items-center justify-center px-4">
          <div className={`text-center max-w-6xl mx-auto duration-1200 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12'}`}>
            <p className="font-cormorant italic text-xl mb-3 drop-shadow">
              <span className="w-2 h-2 bg-[var(--primary)] rounded-full mr-2 animate-pulse" />
              {heroData.lore}
            </p>

            <h1 className="font-cinzel text-3xl md:text-4xl lg:text-5xl font-bold mb-6 leading-tight">
              {headingSentences.map((sentence, i) => (
                <span key={i} className="block">
                  {sentence}.
                  {i === headingSentences.length - 1 && (
                    <span className="ml-1 animate-pulse">|</span>
                  )}
                </span>
              ))}
            </h1>

            <p className="font-cormorant text-lg md:text-xl lg:text-2xl text-[var(--muted-foreground)] mb-8 italic leading-relaxed max-w-4xl mx-auto">
              {heroData.subheading}
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
              <Button
                asChild
                size="lg"
                className="font-cinzel text-lg px-8 py-6 bg-gradient-to-r from-[var(--primary)] to-[var(--accent)] hover:opacity-90 transition-all duration-300 shadow-lg"
              >
                <Link href="/login">
                  {heroData.cta}
                </Link>
              </Button>

              <Button
                asChild
                variant="outline"
                size="lg"
                className="font-cinzel text-lg px-8 py-6 border-[var(--border)] hover:bg-[var(--muted)] transition-all duration-300"
              >
                <Link href="/lore">
                  Explore the Mysteries
                </Link>
              </Button>
            </div>

          </div>
        </section>
    )}
