// apps/web/src/components/landing/Header.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import {
  Menu,
  X,
  User,
  LogOut,
  Crown,
  Sword,
  Shield,
  Code,
  Brain,
  Network
} from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import Image from "next/image";

const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const { data: session, isPending } = authClient.useSession();
  const router = useRouter();

  const handleSignOut = async () => {
    await authClient.signOut();
    router.push("/");
  };

  const navigation = [
    { name: "Lore", href: "/lore", icon: Brain },
    { name: "Community", href: "/community", icon: Shield },
    { name: "Leaderboard", href: "/leaderboard", icon: Crown },
  ];

  return (
    <header
      className="relative top-0 left-0 right-0 z-50"
    >
      <div className="flex items-center justify-between h-16 lg:h-20 px-2 md:px-4 lg:px-8">
        <div className="flex items-center space-x-4">
          <Link
            href="/"
            className="font-cinzel text-2xl lg:text-3xl font-bold tracking-wider text-[var(--foreground)] hover:text-[var(--primary)] transition-colors duration-300 group"
          >
            Aethel
          </Link>

        </div>

        {/* Desktop Navigation */}
        <nav className="hidden lg:flex items-center space-x-8">
          {navigation.map((item) => {
            const IconComponent = item.icon;
            return (
              <Link
                key={item.name}
                href={item.href}
                className="flex items-center space-x-2 text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors duration-300 font-cormorant text-lg group"
              >
                <IconComponent className="w-4 h-4 group-hover:text-[var(--primary)] transition-colors" />
                <span>{item.name}</span>
              </Link>
            );
          })}
        </nav>

        {/* User Actions */}
        <div className="flex items-center space-x-4">
          {isPending ? (
            <div className="items-center space-x-3 hidden lg:flex">
              <Skeleton className="h-10 w-24.5 rounded-md" />
            </div>
          ) : session ? (
            <div className="items-center space-x-3 hidden lg:flex">
              {/* User Avatar & Menu */}
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    className="relative flex items-center space-x-2 hover:bg-[var(--muted)] p-2 rounded-lg cursor-pointer"
                  >
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[var(--primary)] to-[var(--accent)] p-[1px]">
                      <Image src={session.user?.image ?? "/default-avatar.png"} alt="User Avatar" width={32} height={32} className="w-full h-full rounded-full bg-[var(--card)] flex items-center justify-center" />
                    </div>
                    <span className="hidden sm:block font-cormorant text-[var(--foreground)]">
                      {session.user?.name || 'Architect'}
                    </span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent
                  align="end"
                  className="w-56 bg-[var(--card)] border-[var(--border)] shadow-xl"
                >
                  <div className="px-3 py-2">
                    <p className="text-sm font-medium text-[var(--foreground)]">
                      {session.user?.name || 'Architect'}
                    </p>
                    <p className="text-xs text-[var(--muted-foreground)]">
                      {session.user?.email}
                    </p>
                  </div>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem asChild>
                    <Link href="/dashboard" className="flex items-center cursor-pointer">
                      <Code className="w-4 h-4 mr-2" />
                      Command Center
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem asChild>
                    <Link href="/profile" className="flex items-center cursor-pointer">
                      <User className="w-4 h-4 mr-2" />
                      Profile
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem asChild>
                    <Link href="/skilltree" className="flex items-center cursor-pointer">
                      <Network className="w-4 h-4 mr-2" />
                      Skill Tree
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem
                    onClick={handleSignOut}
                    className="text-[var(--destructive)] focus:text-[var(--destructive)] cursor-pointer"
                  >
                    <LogOut className="w-4 h-4 mr-2" />
                    Sign Out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ) : (
            <div className="items-center space-x-3 hidden lg:flex cursor-pointer">
              <Link href="/login">
                <Button
                  className="bg-gradient-to-r from-[var(--primary)] to-[var(--accent)] text-[var(--primary-foreground)] hover:opacity-90 transition-opacity font-cormorant px-6 cursor-pointer"
                >
                  Begin Your Oath
                </Button>
              </Link>
            </div>
          )}

          {/* Mobile Menu Button */}
          <Button
            variant="ghost"
            size="sm"
            className="lg:hidden p-2"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            {isMenuOpen ? (
              <X className="w-5 h-5 text-[var(--foreground)]" />
            ) : (
              <Menu className="w-5 h-5 text-[var(--foreground)]" />
            )}
          </Button>
        </div>
      </div>

      {/* Mobile Navigation Menu */}
      {isMenuOpen && (
        <div className="lg:hidden absolute top-full left-0 right-0 bg-[var(--background)]/95 backdrop-blur-md border-b border-[var(--border)]/50 shadow-xl">
          <div className="px-4 py-6 space-y-4">
            {navigation.map((item) => {
              const IconComponent = item.icon;
              return (
                <Link
                  key={item.name}
                  href={item.href}
                  className="flex items-center space-x-3 text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors duration-300 font-cormorant text-lg py-2"
                  onClick={() => setIsMenuOpen(false)}
                >
                  <IconComponent className="w-5 h-5" />
                  <span>{item.name}</span>
                </Link>
              );
            })}

            {!session && (
              <div className="pt-4 border-t border-[var(--border)] space-y-3">
                <Link
                  href="/login"
                  className="block w-full"
                  onClick={() => setIsMenuOpen(false)}
                >
                  <Button
                    variant="outline"
                    className="w-full font-cormorant"
                  >
                    Enter the Realm
                  </Button>
                </Link>
                <Link
                  href="/login"
                  className="block w-full"
                  onClick={() => setIsMenuOpen(false)}
                >
                  <Button
                    className="w-full bg-gradient-to-r from-[var(--primary)] to-[var(--accent)] text-[var(--primary-foreground)] font-cormorant"
                  >
                    Begin Your Oath
                  </Button>
                </Link>
              </div>
            )}
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;

// apps/web/src/components/Header.svelte
<script>
  import { page } from '$app/stores'; // SvelteKit's store for page data
  import { onMount } from 'svelte';

  export let transparent = true;
  
  // --- IMPROVEMENT 1: State for Mobile Menu ---
  let mobileMenuOpen = false;

  // --- IMPROVEMENT 2: Placeholder for User State ---
  // In a real app, this would come from a store: `import { user } from '$lib/stores/authStore';`
  let user = null; // or { name: 'Architect', avatar: '/img/avatar.png' }

  // Close mobile menu on navigation
  $: if ($page.url.pathname) {
    mobileMenuOpen = false;
  }
</script>

<!-- The w-full class is moved to a container div to handle sticky positioning correctly -->
<div class={`w-full z-20 transition-colors duration-300
  ${transparent && !mobileMenuOpen ? 'absolute top-0 left-0' : 'bg-slate-900/80 backdrop-blur-lg sticky top-0 shadow-xl'}
`}>
  <header class="px-6 md:px-12 py-4 flex justify-between items-center font-cinzel uppercase tracking-wider text-white text-sm">
    <!-- Logo -->
    <a href="/" class="text-2xl md:text-3xl font-bold tracking-widest text-white drop-shadow-md hover:scale-105 transition-transform">
      Aethel<span class="text-slate-400">.</span>
    </a>

    <!-- Desktop Navigation -->
    <nav class="space-x-6 hidden md:block text-slate-300 font-medium">
      <!-- IMPROVEMENT 3: Active Link Styling -->
      <a href="/start" class="hover:text-white transition" class:text-white={$page.url.pathname === '/start'}>Start</a>
      <a href="/lore" class="hover:text-white transition" class:text-white={$page.url.pathname === '/lore'}>Lore</a>
      <a href="/quests" class="hover:text-white transition" class:text-white={$page.url.pathname === '/quests'}>Quests</a>
      <a href="/pvp" class="hover:text-white transition" class:text-white={$page.url.pathname === '/pvp'}>PVP</a>
    </nav>

    <!-- Right Side: Auth State & Mobile Menu Toggle -->
    <div class="flex items-center space-x-4">
      <!-- IMPROVEMENT 4: Authenticated State -->
      <div class="hidden md:block">
        {#if user}
          <a href="/profile" class="flex items-center space-x-2 group">
            <span class="font-ebg normal-case group-hover:text-white text-slate-300">{user.name}</span>
            <img src={user.avatar} alt="User Avatar" class="w-8 h-8 rounded-full border-2 border-slate-500 group-hover:border-white transition"/>
          </a>
        {:else}
          <a 
            href="/login" 
            class="bg-slate-700/50 px-4 py-1.5 rounded-md hover:bg-slate-700/90 transition font-ebg shadow-md text-white border border-slate-600"
          >
            Log In
          </a>
        {/if}
      </div>

      <!-- CRITICAL: Mobile Menu Hamburger Button -->
      <button 
        on:click={() => mobileMenuOpen = !mobileMenuOpen}
        class="md:hidden z-30 p-2"
        aria-label="Toggle navigation menu"
      >
        <!-- Simple hamburger/close icon with transitions -->
        <div class="w-6 h-0.5 bg-white mb-1.5 transition-all duration-300" class:rotate-45={mobileMenuOpen} class:translate-y-2={mobileMenuOpen}></div>
        <div class="w-6 h-0.5 bg-white transition-all duration-300" class:opacity-0={mobileMenuOpen}></div>
        <div class="w-6 h-0.5 bg-white mt-1.5 transition-all duration-300" class:-rotate-45={mobileMenuOpen} class:-translate-y-2={mobileMenuOpen}></div>
      </button>
    </div>
  </header>

  <!-- Mobile Menu Panel -->
  {#if mobileMenuOpen}
    <div 
      class="md:hidden absolute top-full left-0 w-full bg-slate-900/95 backdrop-blur-lg flex flex-col items-center space-y-6 py-8 shadow-2xl"
    >
      <a href="/start" class="text-slate-300 hover:text-white text-xl">Start</a>
      <a href="/lore" class="text-slate-300 hover:text-white text-xl">Lore</a>
      <a href="/quests" class="text-slate-300 hover:text-white text-xl">Quests</a>
      <a href="/pvp" class="text-slate-300 hover:text-white text-xl">PVP</a>
      <hr class="w-3/4 border-slate-700"/>
      {#if user}
        <a href="/profile" class="text-white text-xl">{user.name}'s Profile</a>
        <a href="/logout" class="bg-red-600/80 px-6 py-2 rounded text-lg">Log Out</a>
      {:else}
        <a href="/login" class="bg-slate-700/80 px-8 py-2 rounded text-lg">Log In</a>
      {/if}
    </div>
  {/if}
</div>
