// apps/web/src/components/SignUpForm.tsx
import { authClient } from "@/lib/auth-client";
import { useForm } from "@tanstack/react-form";
import { toast } from "sonner";
import z from "zod";
import Loader from "./loader";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { useRouter } from "next/navigation";

export default function SignUpForm() {
  const router = useRouter();
  const { isPending } = authClient.useSession();

  const form = useForm({
    defaultValues: {
      email: "",
      password: "",
      name: "",
    },
    onSubmit: async ({ value }) => {
      await authClient.signUp.email(
        {
          email: value.email,
          password: value.password,
          name: value.name,
        },
        {
          onSuccess: () => {
            router.push("/dashboard");
            toast.success("Sign up successful");
          },
          onError: (error) => {
            toast.error(error.error.message);
          },
        },
      );
    },
    validators: {
      onSubmit: z.object({
        name: z.string().min(2, "Name must be at least 2 characters"),
        email: z.email("Invalid email address"),
        password: z.string().min(8, "Password must be at least 8 characters"),
      }),
    },
  });

  if (isPending) {
    return <Loader />;
  }

  return (
    <form
      className="bg-white/10 backdrop-blur-md p-8 rounded-xl shadow-2xl w-full max-w-md mx-auto flex flex-col gap-6 border border-white/10"
      onSubmit={(e) => {
        e.preventDefault();
        e.stopPropagation();
        void form.handleSubmit();
      }}
    >
      <div>
        <form.Field name="name">
          {(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name} className="block text-sm font-medium text-white mb-1">Architect's Name</Label>
              <Input
                id={field.name}
                name={field.name}
                type="text"
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
                className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 text-white placeholder-white/50 focus:outline-none focus:border-white/40 transition shadow-sm"
                placeholder="Enter your name"
                required
              />
              {field.state.meta.errors.map((error) => (
                <p key={error?.message} className="text-red-400 text-sm font-cormorant italic">{error?.message}</p>
              ))}
            </div>
          )}
        </form.Field>
      </div>
      {/* Email Field */}
      <div>
        <form.Field name="email">
          {(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name} className="block text-sm font-medium text-white mb-1">Glyph (Email)</Label>
              <Input
                id={field.name}
                name={field.name}
                type="email"
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
                className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 text-white placeholder-white/50 focus:outline-none focus:border-white/40 transition shadow-sm"
                placeholder="Enter your glyph"
                required
              />
              {field.state.meta.errors.map((error) => (
                <p key={error?.message} className="text-red-400 text-sm font-cormorant italic">{error?.message}</p>
              ))}
            </div>
          )}
        </form.Field>
      </div>
      {/* Password Field */}
      <div>
        <form.Field name="password">
          {(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name} className="block text-sm font-medium text-white mb-1">Secret Rune (Password)</Label>
              <Input
                id={field.name}
                name={field.name}
                type="password"
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
                className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 text-white placeholder-white/50 focus:outline-none focus:border-white/40 transition shadow-sm"
                placeholder="Enter your secret rune"
                required
              />
              {field.state.meta.errors.map((error) => (
                <p key={error?.message} className="text-red-400 text-sm font-cormorant italic">{error?.message}</p>
              ))}
            </div>
          )}
        </form.Field>
      </div>
      {/* Submit Button */}
      <form.Subscribe>
        {(state) => (
          <Button
            type="submit"
            className="w-full bg-[#0B1014]/80 text-white py-2 rounded font-ebg text-lg shadow-lg hover:bg-[#0B1014] transition cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed tracking-wide"
            disabled={!state.canSubmit || state.isSubmitting}
          >
            {state.isSubmitting ? "Forging Sigil…" : "Forge Sigil"}
          </Button>
        )}
      </form.Subscribe>
    </form>
  );
}

// apps/web/src/components/SignUpForm.svelte
<script lang="ts">
  import { createForm } from '@tanstack/svelte-form';
  import z from 'zod/v4';
  import { authClient } from '$lib/auth-client';
  import { goto } from '$app/navigation';
  import FormField from './FormField.svelte';

  // IMPROVEMENT: Add a state for API errors
  let apiError = $state<string | null>(null);


  const validationSchema = z.object({
    name: z.string().min(2, 'Name must be at least 2 characters'),
    email: z.email('Invalid email address'),
    password: z.string().min(8, 'Password must be at least 8 characters'),
  });

  const form = createForm(() => ({
    defaultValues: { name: '', email: '', password: '' },
    onSubmit: async ({ value }) => {
      apiError = null;
      await authClient.signUp.email(
        {
          email: value.email,
          password: value.password,
          name: value.name,
        },
        {
          onSuccess: () => goto('/dashboard'),
          onError: (error) => {
            apiError = error.error.message || 'Sign up failed. Please try again.';
          },
        }
      );
    },
    validators: { onSubmit: validationSchema },
  }));
</script>

<form
  class="bg-white/10 backdrop-blur-md p-6 rounded-lg shadow-lg w-full max-w-md space-y-4"
  onsubmit={(e) => { e.preventDefault(); e.stopPropagation(); form.handleSubmit(); }}
>
  <!-- Name Field -->
  <form.Field name="name">
    {#snippet children(field)} <FormField {field} label="Architect's Name" /> {/snippet}
  </form.Field>

  <!-- Email Field -->
  <form.Field name="email">
    {#snippet children(field)} <FormField {field} label="Glyph (Email)" type="email" /> {/snippet}
  </form.Field>

  <!-- Password Field -->
  <form.Field name="password">
    {#snippet children(field)} <FormField {field} label="Secret Rune (Password)" type="password" /> {/snippet}
  </form.Field>

  <!-- IMPROVEMENT: Display API error here -->
  {#if apiError}
    <p class="text-center text-red-400 bg-red-900/30 p-2 rounded-md">{apiError}</p>
  {/if}

  <!-- Submit Button -->
  <form.Subscribe selector={(state) => ({ canSubmit: state.canSubmit, isSubmitting: state.isSubmitting })}>
    {#snippet children(state)}
      <button type="submit" class="w-full bg-[#0B1014]/80 text-white py-2 rounded font-ebg hover:bg-[#0B1014] transition" disabled={!state.canSubmit || state.isSubmitting}>
        {state.isSubmitting ? 'Summoning...' : 'Forge Sigil'}
      </button>
    {/snippet}
  </form.Subscribe>
</form>
